version: "3"

services:
  api:
    build: ./vtrack_api
    command: gunicorn vtrack.wsgi:application -e VTRACK_ENV=${VTRACK_ENV:-development} --chdir=/vtrack/src -b=0.0.0.0:8000 -w=4 -t=10
    container_name: "vTrack-Backend"
    environment:
      VTRACK_ENV: ${VTRACK_ENV:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: vtrack:api
    # ports:
    #   - "8000:8000"
    restart: always
    volumes:
      - ./vtrack_api:/vtrack
      
  webui:
    build: ./vtrack_webui
    command: bash -c "npm i && npm run dev"
    container_name: "vTrack-Frontend"
    environment:
      NODE_ENV: ${NODE_ENV:-local}
    image: vtrack:webui
    # ports:
    #   - "4000:4000"
    restart: always
    volumes:
      - ./vtrack_webui:/vtrack
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: "vTrack-Nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      -  /etc/ssl/certs/innovasolutions-WC-24-25:/etc/ssl/certs
      - ./vtrack_api/static:/static
      - ./vtrack_api/media:/media
      - ./vtrack_webui/dist:/dist
    depends_on:
      - webui
